"""posts table

Revision ID: 8caf29dffd43
Revises: f9e6c2222679
Create Date: 2019-04-23 18:18:16.378377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8caf29dffd43'
down_revision = 'f9e6c2222679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posttags',
    sa.Column('tagid', sa.Integer(), nullable=True),
    sa.Column('postid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postid'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tagid'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posttags')
    op.drop_table('tag')
    # ### end Alembic commands ###
