"""add title and abs to Post

Revision ID: f9e6c2222679
Revises: 42b8aabebe06
Create Date: 2019-04-10 21:29:26.343430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e6c2222679'
down_revision = '42b8aabebe06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('abs', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.drop_column('post', 'abs')
    # ### end Alembic commands ###
